import os
import subprocess
from typing import Dict


def run_ffmpeg_command(ffmpeg_command: str) -> Dict[str, object]:
    """
    Execute an FFmpeg command using subprocess.

    Design principles:
    - No validation
    - No command modification
    - No retries
    - Pure execution + logging

    Args:
        ffmpeg_command (str):
            FFmpeg command generated by c_chain.

    Returns:
        Dict[str, object]:
            {
              "command": str,
              "returncode": int,
              "stdout": str,
              "stderr": str,
              "success": bool
            }
    """

    if "ffmpeg" in ffmpeg_command and "-y" not in ffmpeg_command:
        ffmpeg_command = ffmpeg_command.replace("ffmpeg", "ffmpeg -y", 1)

    try:
        process = subprocess.run(
            ffmpeg_command,
            shell=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=30
        )

        result = {
            "command": ffmpeg_command,
            "returncode": process.returncode,
            "stdout": process.stdout,
            "stderr": process.stderr,
            "success": process.returncode == 0,
        }

    except Exception as e:
        result = {
            "command": ffmpeg_command,
            "returncode": -1,
            "stdout": "",
            "stderr": str(e),
            "success": False,
        }

    return result



def resolve_paths(command: str, env: dict) -> str:

    input_dir = os.path.normpath(env['input_video_dir'])
    output_dir = os.path.normpath(env['output_dir'])

    command = command.replace("mv_", f"{input_dir}{os.sep}mv_")

    if "output.mp4" in command:
        command = command.replace("output.mp4", os.path.join(output_dir, "output.mp4"))

    return command


# ------------------------------------------------------------
# Execution
# ------------------------------------------------------------
if __name__ == "__main__":
    test_command = "ffmpeg -version"
    output = run_ffmpeg_command(test_command)

    print("\n===== FFmpeg Executor Test =====")
    for k, v in output.items():
        print(f"{k}:")
        print(v)
        print("-" * 50)